### ISSUE TITLE
Error upgrading: "Group 'visitors' already has permission 'ffsync.main' enabled"

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/ffsync_ynh#14]
Attempting to upgrade to the latest version of Firefox Sync fails with the following error:

```
Warning: Group 'visitors' already has permission 'ffsync.main' enabled
Warning: The permission was also implicitly granted to 'all_users' because it is required to allow the special group 'visitors'
Warning: Could not update permission 'ffsync.main' : An error occurred during LDAP operation
Warning: [ERR] Upgrade failed.
```
Using Yunohost 3.7.0.4 over Debian 9 Stretch.

**Comment by Josue-T** [comment]
Well, it's a core side bug. I'll investigate on this side.

**Comment by Josue-T** [comment]
Are your instance up to date ?

**Comment by Josue-T** [comment]
Do you have a full log of your upgrade ?
Are you sure that `slapd` was running before your upgrade ?

**Comment by Josue-T** [comment]
I've tried on my VM on yunohost unstable and I didn't got this issue.

**Comment by csolisr** [comment]
Hello, I found out that `slapd` was indeed not running before the upgrade, reenabling it made the upgrade finally work. Closing.
