### ISSUE TITLE
bug with the new version (1.8.0~ynh1 (74413b6))

### ISSUE THREAD

**Issue by Saimyx** [YunoHost-Apps/ffsync_ynh#18]
With 1.8.0~ynh1 (74413b6), bookmarks, password, configuration, history and list of addons installed don't work.
The function to send an tab work sometimes.

I had restored the old version (1.8.0~ynh1 (d24e966)) and it works !

My Yunohost server is an VPS x64 3.7.1.1 (stable).

**Comment by Josue-T** [comment]
Hello,

Honestly, I haven't tested this new version. I thought that the master branch was enough stable to use but looking this I think that it might be better to keep the official version 1.8.0.

**Comment by Josue-T** [comment]
Should be fixed in testing

**Comment by scharc** [comment]
I am having the same issue.

**Comment by PatriceF31** [comment]
Hello,
I have the same problem, bookmarks not synchronize with 1.8.0~ynh1.
Regards

**Comment by PatriceF31** [comment]
Sync is resolved between computers with version : 1.8.0~ynh1 (232bdf2)
But still not with android device.

**Comment by Saimyx** [comment]
Yes, it work on computers !
For android, I have the same, but it was already with versions 1.8.0~ynh1 (74413b6) and 1.8.0~ynh1 (d24e966).

**Comment by Josue-T** [comment]
Should be fixed now. Please reopen if it's still not solved on your side
