### ISSUE TITLE
Python2.7 EOL

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/ffsync_ynh#22]
Hi dear maintainers,
There is now a deprecation warning about Python 2.7 when updating this app. Is there anything we can do to help migrate to Python3 ? Or is this a question for Mozilla to solve ?
Thanks in advance,
-- A ynh fan

**Comment by Josue-T** [comment]
Hello,

The issue is on the Mozilla side and I think Mozilla will never add the support for python3 as Mozilla rewrite completely the sync-server in Rust. So in long term this app will migrate to the new implementation in Rust.

**Comment by Jaxom99** [comment]
Okay, thank you for the clarification. I guess you can close the issue then :) (or leave it open, for others to see it easily).

**Comment by pyrignis** [comment]
Hi.
Has anyone found time to work on porting the ynh app to the new Rust server? any place to track theses changes?

**Comment by Josue-T** [comment]
When a new upstream version will be out with the rust implementation the package will be updated.

**Comment by zecamigo** [comment]
Should ffsync be flagged as broken?
I'm facing the same problem. Tried on yh 4.3.3 and then on yh 4.3.4.2. It crashed (froze) the server on both occasions.
