### ISSUE TITLE
Upgrade error - restore error

### ISSUE THREAD

**Issue by jacen05** [YunoHost-Apps/ffsync_ynh#29]
Hello,

System info:
- Yunohost version: 4.2.4
- All system packages up-to-date
- Hardware: VPS
- Other upgrades of Yunohost applications have been done the same day without problem

I tried to upgrade from 1.8.0 to 1.9.1, but the upgrade failed.
The yunohost log is [here](https://paste.yunohost.org/raw/ayisekefiy).
The main problem seems to be the line "Packages need to be removed but remove is disabled." => the script tried to remove ffsync-ynh-deps but could not do it.
This is the first problem.

Second problem: following the upgrade failure, yunohost tried to restore the previous version. This also failed, as you can see at the end of the log. The error is that "This backup archive can not be restored because it comes from a too-old YunoHost version.". After looking at this problem on Yunohost forum, I saw [this post](https://forum.yunohost.org/t/impossible-to-restore-after-a-fail-update-of-synapse-yuno-testing-4-2-2/15447/5) mentionning that there was a problem in the backup JSON file. So I manually edited the file, and tried to restore it again, but got another error, this time related to the service uwsgi-app@ffsync.service when Yunohost tried to launch it. The log is [here](https://paste.yunohost.org/raw/ebehofival).

What can I do to correct that?

Edit: included systeminfo.

**Comment by Josue-T** [comment]
Closing as no more activity on this issue.
