### ISSUE TITLE
Install fails on bullseye due to dependencies that don't exist anymore

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/ffsync_ynh#32]
c.f. https://ci-apps-bullseye.yunohost.org/ci/job/168

```
20719 WARNING Package libmariadbclient-dev is not available, but is referred to by another package.
20720 WARNING This may mean that the package is missing, has been obsoleted, or
20722 WARNING is only available from another source
20722 WARNING However the following packages replace it:
20722 WARNING   libmariadb-dev-compat libmariadb-dev

20723 WARNING Package python-virtualenv is not available, but is referred to by another package.
20723 WARNING This may mean that the package is missing, has been obsoleted, or
20724 WARNING is only available from another source

20727 WARNING Package uwsgi-plugin-python is not available, but is referred to by another package.
20729 WARNING This may mean that the package is missing, has been obsoleted, or
20730 WARNING is only available from another source

20731 WARNING E: Package 'python-virtualenv' has no installation candidate
20731 WARNING E: Package 'uwsgi-plugin-python' has no installation candidate
20733 WARNING E: Package 'libmariadbclient-dev' has no installation candidate
```

Sounds like ffsync (at least the app?) depends on a lot on python2 which won't be available anymore

**Comment by yalh76** [comment]
ffsync require python 2.7 no more available for Bullseye ... maybe using `ynh_install_python` would allow to install python2 on bullseye ?

**Comment by alexAubin** [comment]
![](https://thumbs.gfycat.com/CorruptShallowAfricancivet-size_restricted.gif)

**Comment by alexAubin** [comment]
I would naively expect that if the upstream is maintained, they would switch to Python3 soon™ :cry:

**Comment by yalh76** [comment]
we will wait then the upstream upgrade ^^

**Comment by Josue-T** [comment]
The upstream is migrating to rust but it take a long time...

**Comment by yalh76** [comment]
> 
> 
> The upstream is migrating to rust but it take a long time...

oupsi²... well only way would be to use ynh_install_python .... did we try a shot ?

**Comment by yalh76** [comment]
> 
> 
> The upstream is migrating to rust but it take a long time...

Is it https://github.com/mozilla-services/syncstorage-rs the rust implementation ?

**Comment by Josue-T** [comment]
cf https://github.com/YunoHost-Apps/ffsync_ynh/issues/22

**Comment by csolisr** [comment]
Sorry for necroposting, but this issue doesn't seem to have had any progress. Has somebody figured how to build the Rust version of Firefox Sync yet?

**Comment by Jaxom99** [comment]
One of their developers answered basic questions here : https://github.com/mozilla-services/syncstorage-rs/issues/1246 
:arrow_right: So I guess it's time for a new package in ynh ? Is there any existing one using rust already ? Maybe a new forum thread would be more useful at this step...

**Comment by csolisr** [comment]
Regarding packages using Rust that you can use as a base, Vaultwarden is one of them: https://github.com/YunoHost-Apps/vaultwarden_ynh/blob/master/scripts/install

**Comment by csolisr** [comment]
Now then, it seems like this version of Sync does require an on-premises accounts server: https://github.com/mozilla/fxa/tree/main/packages/fxa-auth-server (but fortunately it seems like that one is based on Node / Redis so it should be more straightforward to package)

**Comment by Josue-T** [comment]
> One of their developers answered basic questions here : [mozilla-services/syncstorage-rs#1246](https://github.com/mozilla-services/syncstorage-rs/issues/1246) arrow_right So I guess it's time for a new package in ynh ? Is there any existing one using rust already ? Maybe a new forum thread would be more useful at this step...

Hello,

Thanks for the answer, but does the tokenserver-rs is it ready ?

**Comment by Jaxom99** [comment]
As I understand the answers in the linked ticket, there is no need for other program than syncstorage-rs. Just as FFSync did not manage authentication but just the storage of data, the new service can be used in conjunction with auth service provided by Mozilla.
But in the end, I'm not a developer so I was just raising interest in making it happen :smiley_cat:
