### ISSUE TITLE
Installation of ffsync fails on Yunohost 4.5.3 Buster

### ISSUE THREAD

**Issue by edo0** [YunoHost-Apps/ffsync_ynh#36]
### Describe the bug

ffsync does not install on latest Yunohost 4.5.3 (stable), based on Debian Buster. Instead, it gives an error (please find log below), aborts and reverts the installation process. 

### Context

- Hardware: *RPi3B+ at home*
- YunoHost version: *4.5.3*
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: latest stable available on Yunohost

### Steps to reproduce

- If you performed a command from the CLI, the command itself is enough. For example:
  ''' sudo yunohost app install ffsync --label FF-sync '''

### Expected behavior
*Installation of ffsync*

### Logs
[https://paste.yunohost.org/raw/hoduxojicu](https://paste.yunohost.org/raw/hoduxojicu)

**Comment by csolisr** [comment]
Possibly related to issue #32

**Comment by Josue-T** [comment]
> Possibly related to issue #32

No

It look like that the build was killed for an unknown reason. Maybe you didn't have enough resource to build some binary. Maybe you could retry.

**Comment by Josue-T** [comment]
Closing as no more activity on this issue.
