### ISSUE TITLE
Firefox sync auth server

### ISSUE THREAD

**Issue by plopoyop** [YunoHost-Apps/ffsync_ynh#8]
Hi,
It is now possible to host your own authentication server instead of using mozilla's server
https://github.com/mozilla/fxa-auth-server/

It is a nodejs server and it look like there is no ldap support.
It worth keeping a reminder if anyone have time to check for a yunohost integration.

**Comment by Jibec** [comment]
Thank you, it looks interesting!

**Comment by Josue-T** [comment]
Closing as the link above look like no more maintained.

**Comment by Gredin67** [comment]
Is this the maintained version https://github.com/mozilla/fxa/ ?
