### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/ffsync_ynh#9]
In Yunohost this package is labelled as **not working**.
But I do not see any open issues here... and the parent project has not been active for over 3 years.

Is this project dead?

**Comment by Josue-T** [comment]
Hello, there are this PR https://github.com/YunoHost-Apps/ffsync_ynh/pull/6 which is waiting to be merged, so it's not really dead.

**Comment by alexAubin** [comment]
#6 has been merged so maybe we can close this issue ? The app is still flagged as not working though (I guess the CI did not re-test it)

Also it's confusing that yunohost-app is the default branch instead of master :s

**Comment by Josue-T** [comment]
Well,

I changed the branche to master. It still are a problem that I need to fix when I find time...

**Comment by Josue-T** [comment]
Should be fine now.

Don't hesitate to reopen this issue if you find any other issues
